name: pyhc-core
channels:
  - conda-forge
dependencies:
  - aiofiles=23.1.0
  - aioftp=0.21.4
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - aom=3.5.0
  - appdirs=1.4.4
  - asdf=2.14.3
  - asdf-astropy=0.3.0
  - asdf-coordinates-schemas=0.1.0
  - asdf-standard=1.0.3
  - asdf-transform-schemas=0.3.0
  - asdf-unit-schemas=0.1.0
  - asteval=0.9.29
  - astropy=5.2.1
  - astropy-healpix=0.7
  - async-timeout=4.0.2
  - attrs=22.2.0
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.11.2
  - blosc=1.21.3
  - bokeh=2.4.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.7.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cdasws=1.7.42
  - cdflib=0.4.9
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charls=2.4.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contourpy=1.0.7
  - cryptography=39.0.1
  - curl=7.88.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.2.1
  - dask-core=2023.2.1
  - dav1d=1.0.0
  - decorator=5.1.1
  - distributed=2023.2.1
  - drms=0.6.3
  - exceptiongroup=1.1.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.1.0
  - future=0.18.3
  - giflib=5.2.1
  - glymur=0.12.2
  - greenlet=2.0.2
  - h5netcdf=1.1.0
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - hypothesis=6.68.2
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.25.1
  - importlib-metadata=6.0.0
  - importlib-resources=5.12.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - isodate=0.6.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.88.1
  - libdeflate=1.17
  - libffi=3.4.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libnetcdf=4.9.1
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=15.0.7
  - lmfit=1.1.0
  - locket=1.0.0
  - lxml=4.9.2
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib-base=3.7.0
  - mpl_animators=1.1.0
  - mpmath=1.2.1
  - msgpack-python=1.0.4
  - multidict=6.0.4
  - munkres=1.1.4
  - netcdf4=1.6.2
  - networkx=3.0
  - numexpr=2.8.3
  - numpy=1.24.2
  - openjpeg=2.5.0
  - openssl=3.0.8
  - packaging=23.0
  - pandas=1.5.3
  - parfive=2.0.2
  - partd=1.3.0
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - plasmapy=0.7.0
  - platformdirs=3.0.0
  - pluggy=1.0.0
  - pooch=1.6.0
  - portalocker=2.7.0
  - psutil=5.9.4
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyerfa=2.0.0.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytables=3.7.0
  - pytest=7.2.1
  - pytest-datadir=1.4.1
  - pytest-regressions=2.4.2
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2022.7.1
  - pywavelets=1.4.1
  - pyyaml=6.0
  - reproject=0.10.0
  - requests=2.28.2
  - requests-file=1.5.1
  - requests-toolbelt=0.10.1
  - scikit-image=0.19.3
  - scipy=1.10.1
  - semantic_version=2.10.0
  - setuptools=67.4.0
  - setuptools-scm=7.1.0
  - six=1.16.0
  - snappy=1.1.9
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=2.0.4
  - sunpy=4.1.3
  - tblib=1.7.0
  - tifffile=2023.2.3
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - uncertainties=3.1.7
  - urllib3=1.26.14
  - viresclient=0.11.1
  - wheel=0.38.4
  - xarray=2023.2.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zeep=4.2.1
  - zfp=1.0.0
  - zict=2.2.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
      - geopack==1.0.9
      - hapiclient==0.2.5
      - pysat==3.0.6
      - pyspedas==1.4.23
      - pytplot-mpl-temp==2.1.17
