name: Test Conda environment creation

on: [push]

jobs:
  test-env:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment_core.yml
        activate-environment: pyhc-core

    - name: Check PyHC packages can be imported
      run: |
        python -c "import hapiclient"
        python -c "import plasmapy"
        python -c "import pysat"
        python -c "import pyspedas"
        python -c "import spacepy"
        python -c "import sunpy"
